/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Кластер]
      ,[1]
      ,[2]
      ,[3]
      ,[4]
      ,[5]
      ,[6]
      ,[7]
      ,[8]
      ,[9]
      ,[10]
      ,[11]
      ,[12]
      ,[13]
      ,[14]
      ,[15]
      ,[16]
      ,[17]
      ,[18]
      ,[19]
      ,[20]
      ,[21]
      ,[22]
      ,[23]
      ,[24]
      ,[25]
      ,[26]
  FROM [CoikkoDWH].[dbo].[clusterResults]
  select * from [dbo].[clusterResults]
  order by [Кластер]